services:
  radio-discord-bot:
    build:
      args:
        BUILD_CONFIGURATION: Debug
    volumes:
      - ../src/Worker:/app/Worker
      - ../src/Data:/app/Data
      - ../src/Domain:/app/Domain
      - ../src/Infrastructure:/app/Infrastructure
    entrypoint: ["dotnet", "Worker.dll", "--wait-for-debugger"]
