// <auto-generated />
using Infrastructure.CompiledModels;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DiscordBotContext), typeof(DiscordBotContextModel))]
