// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Infrastructure.CompiledModels
{
    public partial class DiscordBotContextModel
    {
        private DiscordBotContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("45b6d6a4-d2e0-417d-aa8d-8364881d57ae"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var playHistory = PlayHistoryEntityType.Create(this);
            var radioSource = RadioSourceEntityType.Create(this);
            var song = SongEntityType.Create(this);
            var user = UserEntityType.Create(this);

            PlayHistoryEntityType.CreateForeignKey1(playHistory, song);
            PlayHistoryEntityType.CreateForeignKey2(playHistory, user);

            PlayHistoryEntityType.CreateAnnotations(playHistory);
            RadioSourceEntityType.CreateAnnotations(radioSource);
            SongEntityType.CreateAnnotations(song);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.6");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
