name: Run Radio Discord Bot
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing container
        run: |
          docker stop discord-bot || true
          docker rm discord-bot || true

      - name: Remove old image
        run: |
          docker rmi radiodiscordbot:latest || true

      - name: Build new image
        run: |
          docker build -f deployment/Dockerfile -t radiodiscordbot:latest .

      - name: Run new container
        run: |
          docker run -d \
            --name discord-bot \
            --restart unless-stopped \
            -e SpotifySettings__ClientId="${{ secrets.SPOTIFY_CLIENT_ID }}" \
            -e SpotifySettings__ClientSecret="${{ secrets.SPOTIFY_CLIENT_SECRET }}" \
            -e Discord__Token="${{ secrets.DISCORD_TOKEN }}" \
            radiodiscordbot:latest
