name: Run Radio Discord Bot
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing containers
        run: |
          cd deployment && docker compose down || true

      - name: Remove old images
        run: |
          docker rmi radiodiscordbot:latest || true

      - name: Create .env file
        run: |
          echo "POSTGRES_DB=postgres_db" > .env
          echo "POSTGRES_USER=postgres_user" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> .env
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env

      - name: Build and run with Docker Compose
        run: |
          docker compose up -d --build