name: Run Radio Discord Bot

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build
